2013-11-03 23:51:53,218 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap.css
2013-11-03 23:51:54,153 [WARNING] django.request: Not Found: /static/bootstrap.min.js
2013-11-03 23:51:54,156 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap-responsive.css
2013-11-03 23:52:23,681 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap.css
2013-11-03 23:52:24,678 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap-responsive.css
2013-11-03 23:52:24,683 [WARNING] django.request: Not Found: /static/bootstrap.min.js
2013-11-03 23:52:30,389 [WARNING] django.request: Not Found: /accounts/login/
2013-11-03 23:52:37,504 [WARNING] django.request: Not Found: /static/bootstrap.min.js
2013-11-03 23:52:37,507 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap.css
2013-11-03 23:52:38,040 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap-responsive.css
2013-11-03 23:52:40,280 [WARNING] django.request: Not Found: /static/bootstrap.min.js
2013-11-03 23:52:40,282 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap-responsive.css
2013-11-03 23:52:40,286 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap.css
2013-11-03 23:52:42,474 [WARNING] django.request: Not Found: /accounts/login/
2013-11-03 23:53:58,129 [ERROR] django.request: Internal Server Error: /home/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-03 23:54:35,572 [WARNING] django.request: Not Found: /static/bootstrap.min.js
2013-11-03 23:54:35,573 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap-responsive.css
2013-11-03 23:54:35,578 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap.css
2013-11-03 23:54:45,298 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-03 23:55:13,840 [WARNING] django.request: Not Found: /static/css/tourconfig.css
2013-11-03 23:55:13,844 [WARNING] django.request: Not Found: /static/css/jquery-ui.css
2013-11-03 23:55:13,848 [WARNING] django.request: Not Found: /static/bootstrap.min.js
2013-11-03 23:55:13,850 [WARNING] django.request: Not Found: /static/jquery-1.9.1.js
2013-11-03 23:55:13,854 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap-responsive.css
2013-11-03 23:55:13,858 [WARNING] django.request: Not Found: /static/bootstrap/css/bootstrap.css
2013-11-03 23:55:13,886 [WARNING] django.request: Not Found: /static/jquery-ui.js
2013-11-04 00:08:40,159 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:08:42,828 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:08:45,049 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:08:45,946 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:08:49,033 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:08:54,512 [WARNING] django.request: Not Found: /start
2013-11-04 00:09:11,209 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:11:08,159 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:11:49,486 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:14:54,859 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:15:45,164 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:15:53,079 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:16:04,345 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:16:12,513 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
2013-11-04 00:29:08,507 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/devcycle/analysis/views.py", line 62, in home_view
    current_tour = TourConfig.objects.values('tour_id', 'tour_name', 'start_time', 'max_tour_time', 'tour_organization', 'tour_logo', 'dcs_url').latest('pk')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 516, in latest
    return obj.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: TourConfig matching query does not exist.
